spring:
  application:
    name: discovery

server:
  port: 8761
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false